version: "3"
services:
  dev:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /var/app/node_modules
      - .:/var/app

  test:
    build:
      context: .
      dockerfile: ./.docker/ci/Dockerfile
    volumes:
      - /var/app/node_modules
      - .:/var/app
    command: ["npm","run","test"]





